import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { selectAuthState, setAuthState, setUserProfile } from "../store/authSlice";
import { useDispatch, useSelector } from "react-redux";
import Button from '@mui/material/Button';
import Layout from '../components/layout/layout';
import { wrapper } from "../store/store";
import { getMe } from '../utility/request';
const Home: NextPage = () => {
  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <div>
          </div>
        </main>
      </div>
    </Layout>
  )
}
export default Home
